version: '3.8'

services:
  app:
    build: .
    container_name: iphone_service_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      ENVIRONMENT: development
