apiVersion: v1
kind: ConfigMap
metadata:
  name: iphone-service-config
  labels:
    app: iphone-service-pos
data:
  app.yaml: |
    server:
      port: 8080
      environment: production
      base_url: https://api.iphoneservice.com
    
    database:
      max_open_conns: 100
      max_idle_conns: 10
      conn_max_lifetime: 3600s
    
    redis:
      pool_size: 10
      min_idle_conns: 5
      max_conn_age: 3600s
    
    jwt:
      expiry: 24h
      refresh_expiry: 168h
    
    rate_limit:
      requests: 100
      window: 1m
    
    logging:
      level: info
      format: json
    
    monitoring:
      metrics_enabled: true
      health_check_interval: 30s
