apiVersion: apps/v1
kind: Deployment
metadata:
  name: iphone-service-pos
  labels:
    app: iphone-service-pos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iphone-service-pos
  template:
    metadata:
      labels:
        app: iphone-service-pos
    spec:
      containers:
      - name: iphone-service-pos
        image: iphone-service-pos:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: jwt-secret
        - name: JWT_EXPIRY
          value: "24h"
        - name: REFRESH_EXPIRY
          value: "168h"
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: s3-endpoint
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: s3-secret-key
        - name: S3_BUCKET_NAME
          value: "iphone-service"
        - name: S3_REGION
          value: "us-east-1"
        - name: MIDTRANS_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: midtrans-server-key
        - name: MIDTRANS_CLIENT_KEY
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: midtrans-client-key
        - name: MIDTRANS_IS_PRODUCTION
          value: "true"
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: twilio-auth-token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: twilio-phone-number
        - name: FIREBASE_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: iphone-service-secrets
              key: firebase-server-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: iphone-service-config
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
