apiVersion: v1
kind: ServiceMonitor
metadata:
  name: iphone-service-pos-monitor
  labels:
    app: iphone-service-pos
    release: prometheus
spec:
  selector:
    matchLabels:
      app: iphone-service-pos
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: iphone-service-pos-metrics
  labels:
    app: iphone-service-pos
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: iphone-service-pos
